In [2]:
import numpy as np
import pandas as pd

data_set = pd.read_csv('../../data/Iris.csv')

In [3]:
data_set.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [5]:
data_set.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [6]:
data_set.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
X = data_set.iloc[:, 1:5]

In [8]:
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [9]:
Y = data_set.iloc[:, -1]
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [12]:
X = scaler.fit_transform(X)
X[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=1)

In [21]:
prediction = knn.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, prediction)
print(accuracy)

0.9666666666666667

In [33]:
Y_test.values[0:5]

array(['Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor'], dtype=object)

In [25]:
prediction[0:5]

array(['Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor'], dtype=object)

In [27]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, prediction)
cm

array([[10,  0,  0],
       [ 0,  7,  1],
       [ 0,  0, 12]], dtype=int64)

In [34]:
# from sklearn.metrics import precision_score, r2_score, recall_score
# #
# precision = precision_score(Y_test.values, prediction)
# recall = recall_score(Y_test, prediction, average='macro')
# r2 = r2_score(Y_test, prediction)

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [45]:
result = pd.DataFrame(data=[Y_test.values, prediction], index=['Y_test', 'prediction'])
result.transpose()

             Y_test       prediction
0    Iris-virginica   Iris-virginica
1    Iris-virginica   Iris-virginica
2       Iris-setosa      Iris-setosa
3    Iris-virginica   Iris-virginica
4   Iris-versicolor  Iris-versicolor
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7       Iris-setosa      Iris-setosa
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10  Iris-versicolor  Iris-versicolor
11   Iris-virginica   Iris-virginica
12   Iris-virginica   Iris-virginica
13      Iris-setosa      Iris-setosa
14   Iris-virginica   Iris-virginica
15   Iris-virginica   Iris-virginica
16   Iris-virginica   Iris-virginica
17      Iris-setosa      Iris-setosa
18      Iris-setosa      Iris-setosa
19      Iris-setosa      Iris-setosa
20  Iris-versicolor  Iris-versicolor
21  Iris-versicolor   Iris-virginica
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26  Iris-versicolor  Iris-versicolor
27   Iris-virginica   Iris-virginica
28  Iris-versicolor  Iris-versicolor
29      Iris-setosa      Iris-setosa

In [47]:
correct_sum = []

for i in range(1, 20):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, Y_train)
    prediction = knn.predict(X_test)
    correct = np.sum(prediction == Y_test)
    correct_sum.append(correct)

correct_sum

[29, 28, 28, 29, 28, 30, 28, 29, 28, 29, 28, 29, 29, 29, 29, 28, 28, 28, 29]

In [56]:
final_result = pd.DataFrame(data=correct_sum)
final_result.index = final_result.index + 1
final_result

     0
1   29
2   28
3   28
4   29
5   28
6   30
7   28
8   29
9   28
10  29
11  28
12  29
13  29
14  29
15  29
16  28
17  28
18  28
19  29

In [58]:
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, Y_train)
prediction = knn.predict(X_test)
accuracy = accuracy_score(Y_test, prediction)
accuracy

1.0

In [59]:
confusion_matrix(Y_test, prediction)

array([[10,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 12]], dtype=int64)